/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ssnfs.h"

#include <stdio.h> // For printf, etc.
#include <stdlib.h> // For atoi, etc.
#include <string.h> // Needed for various string manipulations.
#include <rpc/rpc.h> // Header for RPC calls.
#include <pwd.h> // Need to get username.

//global variables
#define HOST_NAME "cor.cs.uky.edu"
CLIENT *clnt; 						

//function prototypes
int Open(char filename[]);
void Read(int fd, char buffer[], int bytesToRead);
void Write(int fd, char message[], int bytepos);
void List();
void Delete(char filename[]);
void Close(int fd);

//main function
int main (int argc, char *argv[])
{
	if (argc != 1) 
	{
		printf ("usage: %s \n", argv[0]);
		exit (1);
	}
	
	//assign value to client within int main(). Value should be globally visible.
	
	clnt = clnt_create (HOST_NAME, SSNFSPROG, SSNFSVER, "udp");

	if (clnt == NULL) 
	{
		clnt_pcreateerror (HOST_NAME);
		exit (1);
	}

	//ssnfsprog_1 (HOST_NAME);
	
	/*practice code <start>*/
	
	int i,j,k;
	int fd1,fd2,fd3;
	char buffer[100];
	
	fd1 = Open("File1"); // opens the file
	
	for (i = 0; i < 20; i++)
	{
		Write(fd1, "funny contents in the file 1", 15);
	}
	
	Close(fd1);
	
	fd2 = Open("File1");
	
	for (j = 0; j < 20; j++)
	{
		Read(fd2, buffer, 10);
		printf("%s\n", buffer);
	}
	
	Close(fd2);
	
	Delete("File1");
	
	List();
	
	/*practice code <end>*/

	exit (0);
}

//******************************
/*wrapper function definitions*/
//******************************

int Open(char filename[])
{
	open_input in;
	open_output *result;
	char *username = getpwuid(geteuid())->pw_name;
	
	strcpy(in.user_name, username);
	strcpy(in.file_name, filename);
	
	result = open_file_1(&in, clnt); //clnt is a global variable
	
	//does it need an & ?
	return result->fd; //return file descritor
}

void Read(int fd, char buffer[], int bytesToRead)
{
	read_input in;
	read_output *result;
	char *username = getpwuid(geteuid())->pw_name;

	strcpy(in.user_name, username);
	in.fd = fd;
	in.numbytes = bytesToRead;

	result = read_file_1(&in, clnt); //clnt is a global variable
	
	//two members in result:
	//result.out_msg.out_msg_len
	//result.out_msg.out_msg_val --> will be data read
	
	strcpy(buffer, result->out_msg.out_msg_val);
	
	//return nothing. buffer will be printed in main().
}

void Write(int fd, char message[], int bytepos)
{
	write_input in;
	write_output *result;
	char *username = getpwuid(geteuid())->pw_name;

	strcpy(in.user_name, username);
	in.fd = fd;
	in.numbytes = bytepos;
	in.buffer.buffer_val = strdup(message);
	in.buffer.buffer_len = strlen(message) + 1;

	result = write_file_1(&in, clnt); //clnt is a global variable

	//two members in result:
	//result.out_msg.out_msg_len
	//result.out_msg.out_msg_val
	
	printf("\n %s \n", result->out_msg.out_msg_val);
	
	//return nothing	
}

void List()
{
	list_input in;
	list_output *result;
	
	char *username = getpwuid(geteuid())->pw_name;
	
	strcpy(in.user_name, username);
	
	result = list_files_1(&in, clnt); //clnt is a global variable

	//two members in result:
	//result.out_msg.out_msg_len
	//result.out_msg.out_msg_val
	
	printf("\n %s \n", result->out_msg.out_msg_val);
	
	//return nothing
}

void Delete(char filename[])
{
	delete_input in;
	delete_output *result;
	char *username = getpwuid(geteuid())->pw_name;
	
	strcpy(in.user_name, username);
	strcpy(in.file_name, filename);
	
	result = delete_file_1(&in, clnt); //clnt is a global variable
	
	//two members in result:
	//result.out_msg.out_msg_len
	//result.out_msg.out_msg_val
	
	printf("\n %s \n", result->out_msg.out_msg_val);
	
	//return nothing
}

void Close(int fd)
{
	close_input in;
	close_output *result;
	
	in.fd = fd;
	
	result = close_file_1(&in, clnt); //clnt is a global variable
	
	//two members in result:
	//result.out_msg.out_msg_len
	//result.out_msg.out_msg_val
	
	printf("\n %s \n", result->out_msg.out_msg_val);
	
	//return nothing
}
